[package]
name = "pkrs"
version = "0.1.0"
edition = "2021"
authors = ["snowdrift"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
reqwest = { version = "0.11.17", features = ["json"] }
tokio = { version = "1", features = ["full"] }
time = { version = "0.3.21", features = ["serde-well-known"] }